apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-dep
  template:
    metadata:
      labels:
        app: todo-dep
    spec:
      containers:
      - image: todo-app:1.2
        name: todo-app
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "3000"
