apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-10-17T14:42:57Z"
  generation: 1
  labels:
    app: todo-dep
  name: todo-dep
  namespace: default
  resourceVersion: "659"
  uid: a613c774-db4a-411a-8c41-3b6edc3d5601
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-dep
    spec:
      containers:
      - image: todo-app:1.2
        imagePullPolicy: IfNotPresent
        name: todo-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-10-17T14:42:57Z"
    lastUpdateTime: "2025-10-17T14:42:57Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-10-17T14:42:57Z"
    lastUpdateTime: "2025-10-17T14:42:57Z"
    message: ReplicaSet "todo-dep-7d6b5cf648" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
