apiVersion: v1
kind: Service
metadata:
  name: todohtml-svc
spec:
  type: ClusterIP
  selector:
    app: todo-dep
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000

