apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-10-17T11:41:15Z"
  generation: 1
  labels:
    app: hashgenerator-dep
  name: hashgenerator-dep
  namespace: default
  resourceVersion: "1116"
  uid: 7e8942b0-7283-4282-832d-093cc15bcd3e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hashgenerator-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hashgenerator-dep
    spec:
      containers:
      - image: omahash:latest
        imagePullPolicy: Always
        name: omahash
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-10-17T11:41:15Z"
    lastUpdateTime: "2025-10-17T11:41:15Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-10-17T11:41:15Z"
    lastUpdateTime: "2025-10-17T11:41:15Z"
    message: ReplicaSet "hashgenerator-dep-68db8dd949" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
