apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hashgenerator-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hash.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hashgenerator-svc
            port:
              number: 8080
