apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logapp-ingress
spec:
  rules:
  - host: logapp.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: logapp-svc
            port:
              number: 2345
